### ISSUE TITLE
你好，请问一下，ctb50.charconll.r和ctb5格式有啥不同的不？

### ISSUE THREAD

**Issue by woshuaizuishuai** [LindgeW/JointCWPDParser#1]

**Comment by LindgeW** [comment]
ctb50.charconll.r是CTB5的字级别版本，而且词内部的依存关系为左向弧(后一个字为前一个字的head)。

**Comment by woshuaizuishuai** [comment]
你好，再想请教一下，ctb50.charconll.r是你对ctb进行预处理得到的么？

**Comment by LindgeW** [comment]
> 你好，再想请教一下，ctb50.charconll.r是你对ctb进行预处理得到的么？

不是的，是标准的数据集，但是你也可以尝试自己按规则去对CTB进行处理转换成char类型

**Comment by woshuaizuishuai** [comment]
你好，请问可以给出一个样式不

**Comment by LindgeW** [comment]
1       新      _       NR#b    NR#b    _       2       #in     _       _
2       华      _       NR#i    NR#i    _       3       #in     _       _
3       社      _       NR#i    NR#i    _       16      NMOD    _       _
4       巴      _       NR#b    NR#b    _       5       #in     _       _
5       黎      _       NR#i    NR#i    _       16      NMOD    _       _
6       ９      _       NT#b    NT#b    _       7       #in     _       _
7       月      _       NT#i    NT#i    _       16      NMOD    _       _
8       １      _       NT#b    NT#b    _       9       #in     _       _
9       日      _       NT#i    NT#i    _       16      NMOD    _       _
10      电      _       NN#b    NN#b    _       16      NMOD    _       _

**Comment by woshuaizuishuai** [comment]
好的，谢谢
