### ISSUE TITLE
GPU加速

### ISSUE THREAD

**Issue by woshuaizuishuai** [LindgeW/JointCWPDParser#4]
你好，请问一下，JointCWPD如何使用GPU加速，试了好几种发现不太行

**Comment by LindgeW** [comment]
> 你好，请问一下，JointCWPD如何使用GPU加速，试了好几种发现不太行

这个里面用embedding做表示存在的一个问题是词向量文件会比较大，一般不会全部加载到显存里面，否则会导致out-of-memory问题，因此这里采用的CPUEmbedding策略（先加载到内容，实际取到的tensor再转移到GPU），因此它的速度会比较慢

**Comment by LindgeW** [comment]
这个里面用embedding做表示存在的一个问题是词向量文件会比较大，一般不会全部加载到显存里面，否则会导致out-of-memory问题，因此这里采用的CPUEmbedding策略（先加载到cpu，实际forward取到的tensor才转移到GPU），因此它的速度会比较慢

**Comment by LindgeW** [comment]
你可以尝试下将pre_char_embedding换成普通的Embedding，只要你显存够大
